import {
  LineChart,
  PieChart,
  Table,
} from "@/components";
import React from "react";
import { panelTypeValues } from "./constants";

const columns = [
  { accessorKey: "rank", header: "rank", size: 25 },
  { accessorKey: "title", header: "title" },
  { accessorKey: "date", header: "date", size: 25 },
  { accessorKey: "genre", header: "genre" },
  { accessorKey: "affinity", header: "affinity", size: 25 },
  { accessorKey: "rating", header: "rating", size: 25 },
  { accessorKey: "trend", header: "trend", size: 25 },
];

const data = [
  {
    rank: 1,
    title: "Grateful Dead",
    genre: "Documentary",
    affinity: 0.54081,
    rating: 2.5,
    trend: 3.5,
  },
  {
    rank: 2,
    title: "Smile Like Yours, A",
    genre: "Comedy|Romance",
    affinity: 0.86221,
    rating: 4.8,
    trend: 4.8,
  },
  {
    rank: 3,
    title: "Metroland",
    genre: "Comedy|Drama",
    affinity: 0.41768,
    rating: 2.4,
    trend: 2.7,
  },
  {
    rank: 4,
    title: "Blackout",
    genre: "Horror|Thriller",
    affinity: 0.76429,
    rating: 3.5,
    trend: 3.1,
  },
  {
    rank: 5,
    title: "Suicide Kings",
    genre: "Comedy|Crime|Drama|Mystery|Thriller",
    affinity: 0.20139,
    rating: 1.3,
    trend: 0.6,
  },
  {
    rank: 6,
    title: "Funny Games",
    genre: "Drama|Horror|Thriller",
    affinity: 0.15052,
    rating: 2.5,
    trend: 0.1,
  },
  {
    rank: 7,
    title: "Fellini: I'm a Born Liar (Fellini: Je Suis um Grand Menteur)",
    genre: "Documentary",
    affinity: 0.93162,
    rating: 4.8,
    trend: 2.8,
  },
  {
    rank: 8,
    title: "Day of the Dead 2: Contagium",
    genre: "Horror|Sci-Fi",
    affinity: 0.54496,
    rating: 1.1,
    trend: 4.3,
  },
  {
    rank: 9,
    title: "Professionals, The",
    genre: "Western",
    affinity: 0.57192,
    rating: 2.2,
    trend: 3.6,
  },
  {
    rank: 10,
    title: "Alien Nation: The Enemy Within",
    genre: "Sci-Fi",
    affinity: 0.2083,
    rating: 4.3,
    trend: 3.4,
  },
  {
    rank: 11,
    title: "Coca-Cola Kid, The",
    genre: "Comedy|Romance",
    affinity: 0.77241,
    rating: 4.6,
    trend: 0.7,
  },
  {
    rank: 12,
    title: "Charlie Chan on Broadway",
    genre: "Comedy|Crime|Mystery|Thriller",
    affinity: 0.21132,
    rating: 1.6,
    trend: 2.9,
  },
  {
    rank: 13,
    title: "Great Beauty, The (Grande Bellezza, La)",
    genre: "Comedy|Drama",
    affinity: 0.56787,
    rating: 3.6,
    trend: 4.6,
  },
  {
    rank: 14,
    title: "SS Experiment Love Camp (Lager SSadis Kastrat Kommandantur)",
    genre: "Horror|War",
    affinity: 0.18915,
    rating: 4.5,
    trend: 2.7,
  },
  {
    rank: 15,
    title: "Gimme the Loot",
    genre: "Drama",
    affinity: 0.79456,
    rating: 4.3,
    trend: 2.1,
  },
  {
    rank: 16,
    title: "Castle, The",
    genre: "Comedy",
    affinity: 0.90448,
    rating: 5.0,
    trend: 1.4,
  },
  {
    rank: 17,
    title: "Mickey's Twice Upon a Christmas",
    genre: "Animation|Children|Comedy",
    affinity: 0.53061,
    rating: 4.1,
    trend: 0.7,
  },
  {
    rank: 18,
    title: "39 Steps, The",
    genre: "Drama|Mystery|Thriller",
    affinity: 0.30672,
    rating: 2.9,
    trend: 3.2,
  },
  {
    rank: 19,
    title: "Vampire Apocalypse",
    genre: "Comedy|Horror",
    affinity: 0.4272,
    rating: 3.5,
    trend: 2.8,
  },
  {
    rank: 20,
    title: "Under the Skin of the City (Zir-e-poost-e Shahr)",
    genre: "Drama",
    affinity: 0.80432,
    rating: 2.8,
    trend: 0.8,
  },
  {
    rank: 21,
    title: "Spin",
    genre: "Children|Drama",
    affinity: 0.16585,
    rating: 1.6,
    trend: 0.6,
  },
  {
    rank: 22,
    title: "Please Vote for Me",
    genre: "Documentary",
    affinity: 0.32855,
    rating: 1.5,
    trend: 0.1,
  },
  {
    rank: 23,
    title: "Mike's New Car",
    genre: "Animation|Comedy",
    affinity: 0.68339,
    rating: 4.5,
    trend: 3.5,
  },
  {
    rank: 24,
    title: "Martyrs",
    genre: "Horror",
    affinity: 0.31188,
    rating: 4.0,
    trend: 3.7,
  },
  {
    rank: 25,
    title: "Mister Roberts",
    genre: "Comedy|Drama|War",
    affinity: 0.81438,
    rating: 3.0,
    trend: 0.2,
  },
  {
    rank: 26,
    title: "Invasion, The",
    genre: "Action|Drama|Horror|Sci-Fi|Thriller",
    affinity: 0.51658,
    rating: 1.1,
    trend: 4.2,
  },
  {
    rank: 27,
    title: "High and Dry",
    genre: "Comedy",
    affinity: 0.72386,
    rating: 3.6,
    trend: 2.6,
  },
  {
    rank: 28,
    title: "American Pimp",
    genre: "Documentary",
    affinity: 0.76014,
    rating: 1.1,
    trend: 4.8,
  },
  {
    rank: 29,
    title: "Sons and Lovers",
    genre: "Drama",
    affinity: 0.08955,
    rating: 1.5,
    trend: 3.0,
  },
  {
    rank: 30,
    title: "Misérables, Les",
    genre: "Crime|Drama|Romance|War",
    affinity: 0.19672,
    rating: 2.4,
    trend: 3.2,
  },
  {
    rank: 31,
    title: "Ennui, L'",
    genre: "Drama|Romance",
    affinity: 0.93086,
    rating: 4.7,
    trend: 1.3,
  },
  {
    rank: 32,
    title: "Goal II: Living the Dream",
    genre: "Action|Drama",
    affinity: 0.13199,
    rating: 3.6,
    trend: 1.3,
  },
  {
    rank: 33,
    title: "Miller's Crossing",
    genre: "Crime|Drama|Film-Noir|Thriller",
    affinity: 0.59047,
    rating: 3.6,
    trend: 1.6,
  },
  {
    rank: 34,
    title: "Münchhausen",
    genre: "Adventure|Comedy|Fantasy",
    affinity: 0.22193,
    rating: 1.9,
    trend: 1.6,
  },
  {
    rank: 35,
    title: "Mistress America",
    genre: "Comedy",
    affinity: 0.92985,
    rating: 1.1,
    trend: 1.8,
  },
  {
    rank: 36,
    title: "Casper's Haunted Christmas",
    genre: "Animation|Children",
    affinity: 0.57135,
    rating: 4.7,
    trend: 1.0,
  },
  {
    rank: 37,
    title: "Thin Blue Line, The",
    genre: "Documentary",
    affinity: 0.04448,
    rating: 1.1,
    trend: 3.4,
  },
  {
    rank: 38,
    title: "Carnage",
    genre: "Comedy|Drama",
    affinity: 0.03199,
    rating: 2.5,
    trend: 4.2,
  },
  {
    rank: 39,
    title: "Replacement Killers, The",
    genre: "Action|Crime|Thriller",
    affinity: 0.99735,
    rating: 1.2,
    trend: 4.6,
  },
  {
    rank: 40,
    title: "Saving Private Ryan",
    genre: "Action|Drama|War",
    affinity: 0.86039,
    rating: 4.6,
    trend: 1.2,
  },
];

const DashboardPanelBody = ({ type }) => {
  switch (type) {
    case panelTypeValues.donut:
      return <PieChart />;
    case panelTypeValues.line:
      return <LineChart />;
    case panelTypeValues.table:
      return <Table columns={columns} data={data} />;

    default:
      return null;
  }
};

export default DashboardPanelBody;
